export const SET_CHILD_NICK_NAME = 'SET_CHILD_NICK_NAME'

export const SET_CHILD_NAME = 'SET_CHILD_NAME'

export const SET_EXPIRATION_DATE = 'SET_EXPIRATION_DATE'

export const SET_JOIN_STATUS = 'SET_JOIN_STATUS'

export const SET_BIND_STATUS = 'SET_BIND_STATUS'
